### ISSUE TITLE
Getting Started | Docker Compose | Unable to run

### ISSUE THREAD

**Issue by etischler1-beebeegee** [terrakube-io/terrakube#2707]
### Feedback

Hi,

Couple of issues when trying to use the getting started -> docker compose flow.

1) the redis service image does not resolve, i swapped this for bitnamilegacy to make progress

2) when running I ran into ssl verification errors. is it possible to provide a config to turn ssl verification OFF? This was on module refresh

3) When running on another laptop that does not have cert issues I was able to get the app running with no error logs. However the pages would not resolve. Can I get confirmation that this workflow still works?

Running on Apple Silicon using Docker

**Comment by alfespa17** [comment]
I fixed some issue last week here

https://github.com/terrakube-io/terrakube/pull/2689

Maybe you can pull the new changes, it should work with version 2.28.0 now

**Comment by etischler1-beebeegee** [comment]
@alfespa17 I tried it this morning, fresh go of it with updated docker an all

**Comment by alfespa17** [comment]
If you follow [this](https://docs.terrakube.io/getting-started/docker-compose), you should not have SSL issues. By the way the example is to run terrakube locally for testing I guess you could modify the code to make it work from a VM I guess

**Comment by pythoninthegrass** [comment]
Looks like you missed the [redis legacy](https://github.com/terrakube-io/terrakube/blob/main/docker-compose/docker-compose.yml#L298) image @alfespa17 

Updating it to `image: docker.io/bitnamilegacy/redis:${TK_REDIS_VERSION}` like @etischler1-beebeegee mentioned got it up and running.

Going through the [quickstart](https://docs.terrakube.io/getting-started/docker-compose) now.

**Comment by alfespa17** [comment]
> Looks like you missed the [redis legacy](https://github.com/terrakube-io/terrakube/blob/main/docker-compose/docker-compose.yml#L298) image [@alfespa17](https://github.com/alfespa17)
> 
> Updating it to `image: docker.io/bitnamilegacy/redis:${TK_REDIS_VERSION}` like [@etischler1-beebeegee](https://github.com/etischler1-beebeegee) mentioned got it up and running.
> 
> Going through the [quickstart](https://docs.terrakube.io/getting-started/docker-compose) now.

I changed later 

https://github.com/terrakube-io/terrakube/blob/4cb78260cd940893074f85aa92e1cd2a07cc8baf/.devcontainer/docker-compose.yml#L264

https://github.com/terrakube-io/terrakube/pull/2710

**Comment by etischler1-beebeegee** [comment]
@pythoninthegrass how'd it go? did you get it working? what OS did you run it on?

**Comment by etischler1-beebeegee** [comment]
incase it is helpful for someone else in the future:

in the documentation it mentions to edit /etc/hosts as the following:
10.25.25.253 terrakube.platform.local
10.25.25.253 terrakube-api.platform.local
10.25.25.253 terrakube-registry.platform.local
10.25.25.253 terrakube-dex.platform.local

swap 10.25.25.253 with localhost to get it to work (in my case)

**Comment by pythoninthegrass** [comment]
> [@pythoninthegrass](https://github.com/pythoninthegrass) how'd it go? did you get it working? what OS did you run it on?

Sorry for the late response. Terrakube didn't fit my org's needs so didn't spend much time with it.
